apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: cart
        tier: app
        project: roboshop
    spec:
      containers:
      - name: cart
        image: vumahesh435/cart:k8
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels: 
    app: cart
    tier: app
    project: roboshop
spec:
  selector:
    app: cart
    tier: app
    project: roboshop
  ports:
  - name: cart-port
    protocol: TCP
    port: 8080
    targetPort: 8080