apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    app: shipping
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: shipping
        tier: app
        project: roboshop
    spec:
      containers:
      - name: shipping
        image: vumahesh435/shipping:k8
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels: 
    app: shipping
    tier: app
    project: roboshop
spec:
  selector:
    app: shipping
    tier: app
    project: roboshop
  ports:
  - name: shipping-port
    protocol: TCP
    port: 8080
    targetPort: 8080