apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: roboshop
  labels:
    app: ratings
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: ratings
        tier: app
        project: roboshop
    spec:
      containers:
      - name: ratings
        image: vumahesh435/ratings:k8
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: roboshop
  labels: 
    app: ratings
    tier: app
    project: roboshop
spec:
  selector:
    app: ratings
    tier: app
    project: roboshop
  ports:
  - name: ratings-port
    protocol: TCP
    port: 8080
    targetPort: 8080