apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels:
    app: web
    tier: web
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      tier: web
      project: roboshop
  template:
    metadata:
      labels:
        app: web
        tier: web
        project: roboshop
    spec:
      containers:
      - name: web
        image: vumahesh435/web:k8
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
  labels: 
    app: web
    tier: web
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    app: web
    tier: web
    project: roboshop
  ports:
  - name: web-port
    protocol: TCP
    port: 80
    targetPort: 80